export const Dproducts=[
    {
    overLay : "img/10.webp",
    img : 'img/luka.webp',
    price : '¥72,565',
    title : 'Filmy fancy dress',
    offer: false,
},
{    overLay : "img/1.webp",
    img : 'img/8.webp',
    price : '¥21,044',
    title : 'Mortimer Furniture',
    offer: "-4%",
    isSold: "Soldout",
    oldPrice : '¥21,769'
},
{    overLay : "img/7.webp",
    img : 'img/18.webp',
    price : '¥13,062',
    title : '1Utensils in holders',
    offer: false,
},
{    overLay : "img/5.webp",
    img : 'img/15.webp',
    price : '¥43,539',
    title : 'Filmy fancy dress',
    offer: false,
},
{    overLay : "img/3.webp",
    img : 'img/7.webp',
    price : '¥7,256',
    title : 'American Ateiler',
    offer: false,
    isSold: 'Soldout'
},
{    overLay : "img/9.webp",
    img : 'img/29_124126ca-3b0d-4c70-85a3-104a8b5282d0.webp',
    price : '¥116,104',
    title : 'Round neck cotton',
    offer: false,
},
{    overLay : "img/8.webp",
    img : 'img/12_2c94f423-ec3c-4fc5-91a8-5e2dacf698f8.webp',
    price : '¥75,468',
    title : 'Kardiel parlor sofa',
    offer: false,
},
{    overLay : "img/6.webp",
    img : 'img/30_a66f06be-82f5-466f-a430-aca56793d244.webp',
    price : '¥101,591',
    title : 'Royal blue depths',
    offer: false,
},
{    overLay : "img/4.webp",
    img : 'img/9.webp',
    price : '¥29,026',
    title : 'Western top and Jeans',
    offer: '-20%',
    oldPrice:'¥36,282'
},
{    overLay : "img/2.webp",
    img : 'img/21.webp',
    price : '¥14,368',
    title : 'B&O Audio Headphone',
    offer: false,
},
]